# Generated by Django 6.1 on 2026-08-30 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='assigned_donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_blood_requests', to='admin_panel.donorprofile'),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='donor_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='donor_response',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Waiting', max_length=20),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='notified_donors',
            field=models.ManyToManyField(blank=True, related_name='notified_blood_requests', to='admin_panel.donorprofile'),
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation', to='admin_panel.bloodrequest'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20),
        ),
    ]
