# Generated by Django 6.1 on 2026-09-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_bloodrequest_assigned_donor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
