# Generated by Django 6.1 on 2026-09-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_donorprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
