# Generated by Django 6.1 on 2026-09-10 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_alter_donorprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='email',
        ),
    ]
