# Generated by Django 6.1 on 2026-08-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_donor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('hospital_name', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('urgency', models.CharField(max_length=20)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
