# Generated by Django 6.1 on 2026-09-08 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_userprofile'),
        ('system', '0003_bloodrequest'),
    ]

    operations = [
    ]
